import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="bg-gray-400 text-red-400">알에스팀1!</h1>
      <div>
        <button className="test-btn">테스트 버튼</button>
      </div>
      <h1 className="bg-gray-400 text-yellow-200">알에스팀2!</h1>

      {/* <a href="/sh">sh</a> */}
      <br />
      <Link href="/sh">
        <a>sh</a>
      </Link>
    </>
  );
};

export default Home;
