import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import Slider from "react-slick";

const Home: NextPage = () => {
  // const [settings1, setSettings1] = useState({
  //   // dots: true, // 지정 콘텐츠 이동 버튼
  //   className: "slicks",
  //   focusOnSelect: true,
  //   centerMode: true,
  //   infinite: false, // 끝으로 갔을 때 첫 번째로 제자리
  //   speed: 500, // 콘텐츠 넘기는 속도 ms단위 (1000ms = 1초)
  //   // centerPadding: "60px",
  //   slidesToShow: 3, // 한 화면이 보이는 콘텐츠 개수
  //   slidesToScroll: 1, // 한 번에 넘어가는 콘텐츠 개수
  //   initialSlide: 0, // 초기 위치
  //   // variableWidth: true
  // });

  const [current, setCurrent] = useState(1);
  // const [currentMain, setCurrentMain] = useState(0);
  // const [currentPage, setCurrentPage] = useState(0);

  const [mainSlick, setMainSlick] = useState(undefined);
  const [pagingSlick, setPagingSlick] = useState(undefined);
  const mainSlickRef = useRef<any>(null);
  const pagingSlickRef = useRef<any>(null);
  useEffect(() => {
    setMainSlick(mainSlickRef.current);
    setPagingSlick(pagingSlickRef.current);
  }, []);
  const mainSettings = {
    className: "main-slick",
    dots: false,
    arrows: false,
    infinite: false,
    // centerMode: true,
    slidesToShow: 5,
    // slidesToScroll: 1,
    swipeToSlide: true,
    speed: 500,
    initialSlide: 0,
    focusOnSelect: true,
    // touchMove: true,
  };
  const pagingSettings = {
    className: "page-slick",
    dots: false,
    arrows: false,
    infinite: false,
    centerMode: true,
    slidesToShow: 1,
    // slidesToScroll: 1,
    swipeToSlide: true,
    speed: 500,
    initialSlide: 0,
    // focusOnSelect: true,
  };
  const onClickPrev = useCallback(
    (ref: any) => () => ref.current.slickPrev(),
    []
  );
  const onClickNext = useCallback(
    (ref: any) => () => ref.current.slickNext(),
    []
  );

  const onClickSlide = (id: number) => {
    setCurrent(id);
    pagingSlickRef.current.slickGoTo(id - 1, true);
    // slickGoTo
  };

  return (
    <>
      <Head>
        <title>slick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>리액트 slick</h1>
        <Link href="/">
          <a>뒤로가기</a>
        </Link>
        <br />
        <Link href="https://react-slick.neostack.com/docs/example/simple-slider/">
          <a target="_blank">공식페이지</a>
        </Link>
        <div>
          npm install react-slick --save @types/react-slick npm install
          <br />
          slick-carousel --save
          <br />
          참고 블로그: https://sirong.tistory.com/38
        </div>
      </div>

      <div style={{ backgroundColor: "#efefef" }}>
        <h2>FocusOnSelect</h2>
        <div>Click on any slide to select and make it current slide</div>
        <Slider
          ref={mainSlickRef}
          // asNavFor={pagingSlick}
          {...mainSettings}
          // swipeEvent={(e) => {
          //   console.log(e);
          // }}
          afterChange={(e) => {
            console.log("after => ", e);
          }}
          beforeChange={(e) => {
            console.log("before => ", e);
            // pagingSlickRef.current.slickGoTo(e, true);
          }}
        >
          <div>
            <div
              style={{
                background: "green",
                height: "100px",
                fontSize: current === 1 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(1)}
            >
              1
            </div>
            {/* <div style={{ background: "green" }}>1</div> */}
          </div>
          <div>
            <div
              style={{
                background: "red",
                height: "100px",
                fontSize: current === 2 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(2)}
            >
              2
            </div>
          </div>
          <div>
            <div
              style={{
                background: "blue",
                height: "100px",
                fontSize: current === 3 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(3)}
            >
              3
            </div>
          </div>
          <div>
            <div
              style={{
                background: "pink",
                height: "100px",
                fontSize: current === 4 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(4)}
            >
              4
            </div>
          </div>
          <div>
            <div
              style={{
                background: "yellow",
                height: "100px",
                fontSize: current === 5 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(5)}
            >
              5
            </div>
          </div>
          <div>
            <div
              style={{
                background: "gray",
                height: "100px",
                fontSize: current === 6 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(6)}
            >
              6
            </div>
          </div>
          <div>
            <div
              style={{
                background: "green",
                height: "100px",
                fontSize: current === 7 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(7)}
            >
              7
            </div>
          </div>
          <div>
            <div
              style={{
                background: "red",
                height: "100px",
                fontSize: current === 8 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(8)}
            >
              8
            </div>
          </div>
          <div>
            <div
              style={{
                background: "blue",
                height: "100px",
                fontSize: current === 9 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(9)}
            >
              9
            </div>
          </div>
          <div>
            <div
              style={{
                background: "pink",
                height: "100px",
                fontSize: current === 10 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(10)}
            >
              10
            </div>
          </div>
          <div>
            <div
              style={{
                background: "yellow",
                height: "100px",
                fontSize: current === 11 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(11)}
            >
              11
            </div>
          </div>
          <div>
            <div
              style={{
                background: "gray",
                height: "100px",
                fontSize: current === 12 ? "5rem" : "1rem",
              }}
              onClick={() => onClickSlide(12)}
            >
              12
            </div>
          </div>
        </Slider>
      </div>
      <div style={{ backgroundColor: "#efefef", marginTop: "100px" }}>
        <Slider
          ref={pagingSlickRef}
          asNavFor={mainSlick}
          {...pagingSettings}
          onSwipe={(e) => {
            console.log(e);
            if (e === "left") setCurrent(current + 1);
            else if (e === "right") setCurrent(current - 1);
          }}
        >
          <div>
            <div
              style={{ background: "green", height: "500px", margin: "50px" }}
            >
              1
            </div>
          </div>
          <div>
            <div style={{ background: "red", height: "500px", margin: "50px" }}>
              2
            </div>
          </div>
          <div>
            <div
              style={{ background: "blue", height: "500px", margin: "50px" }}
            >
              3
            </div>
          </div>
          <div>
            <div
              style={{ background: "pink", height: "500px", margin: "50px" }}
            >
              4
            </div>
          </div>
          <div>
            <div
              style={{ background: "yellow", height: "500px", margin: "50px" }}
            >
              5
            </div>
          </div>
          <div>
            <div
              style={{ background: "gray", height: "500px", margin: "50px" }}
            >
              6
            </div>
          </div>
          <div>
            <div
              style={{ background: "green", height: "500px", margin: "50px" }}
            >
              7
            </div>
          </div>
          <div>
            <div style={{ background: "red", height: "500px", margin: "50px" }}>
              8
            </div>
          </div>
          <div>
            <div
              style={{ background: "blue", height: "500px", margin: "50px" }}
            >
              9
            </div>
          </div>
          <div>
            <div
              style={{ background: "pink", height: "500px", margin: "50px" }}
            >
              10
            </div>
          </div>
          <div>
            <div
              style={{ background: "yellow", height: "500px", margin: "50px" }}
            >
              11
            </div>
          </div>
          <div>
            <div
              style={{ background: "gray", height: "500px", margin: "50px" }}
            >
              12
            </div>
          </div>
        </Slider>
      </div>
    </>
  );
};

export default Home;
